package CalcModule;

/**
* CalcModule/CalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./CalcModule.idl
* Sunday, 28 May, 2023 6:27:52 PM IST
*/

public final class CalcHolder implements org.omg.CORBA.portable.Streamable
{
  public CalcModule.Calc value = null;

  public CalcHolder ()
  {
  }

  public CalcHolder (CalcModule.Calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcModule.CalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcModule.CalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcModule.CalcHelper.type ();
  }

}
