package CalcModule;


/**
* CalcModule/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./CalcModule.idl
* Sunday, 28 May, 2023 6:27:52 PM IST
*/

public interface CalcOperations 
{
  float add (float num1, float num2);
} // interface CalcOperations
