package CalcModule;


/**
* CalcModule/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./CalcModule.idl
* Sunday, 28 May, 2023 6:27:52 PM IST
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
